name: baby_binder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  flutter_riverpod: ^3.2.0
  riverpod: ^3.2.0
  fl_chart: ^1.1.1
  firebase_storage: ^11.6.5
  flutter_launcher_icons: ^0.14.4
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  wakelock_plus: ^1.2.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/icons/

